### PR TITLE
Remove dependency on Half

### PR DESCRIPTION
**Pull request by christophhagen**
## Description

This PR removes the dependency on `Half`, which is currently used to provide a half-precision floating point type. `Float16` was introduced with Swift 5.3, so the dependency is no longer needed.

## Checklist

Ensure that your `pull request` has followed all the steps below:

* [x] Code compilation.
* [x] All tests passing.
* [x] No new SwiftLint issues.
* [ ] Added new unit tests, if applicable.
* [ ] Extended the documentation (including README), if applicable.
* [ ] Updated version in CBORCoding.podspec following [semver](https://semver.org) guidelines.
* [ ] Ran [workflowtests.sh](../../scripts/workflowtests.sh) and passed.
* [ ] Added myself to the [CONTRIBUTORS](../CONTRIBUTORS.md) file.

## Proposed changes

The main changes are:
- Remove the dependency on Half
- Use the native `Float16` type instead

Minor changes are:
- Minor restructuring of large `if-else` statements
- Fixed some linting warnings

## Additional Info

The dependency on `Float16` requires higher minimum deployment targets on all platforms:
- iOS: `9.0` -> `14.0`
- macOS: `10.10` -> `11.0`
- tvOS: `9.0` -> `14.0`
- watchOS: `2.0` -> `7.0`

For systems with swift version lower than `5.3`, the dependency on Half is still needed. In this case the `typealias Float16 = Half` is included. The package descriptions for `4.2` and `5.0` still include the dependency. The correct compilation on older platforms is untested.

### CODE REVIEW

**Comment by dabrahams** [comment]
@SomeRandomiOSDev what's it going to take to get this PR accepted?  The failed "@codacy-production
Codacy Static Code Analysis" gives no clues.

With these changes, the library passes all tests on Windows!

**Comment by dabrahams** [comment]
Argh, for my purposes this is not a fully-complete solution because Float16 is apparently [unavailable on Apple Silicon](https://developer.apple.com/forums/thread/724184).

I wonder if support for CBOR serializing 16-bit floats really needs to be built into the core of this library, or if it could be added as an extension the way we normally would with any user-defined types?

**Comment by dabrahams** [comment]
@christophhagen I took a [first cut](https://github.com/SomeRandomiOSDev/CBORCoding/commit/d1f6ae0869f38e3e674e4a305598d4b57a6cf428) at making it work on x64 macs, but it's clear that some of the old logic needs to be restored because the [build is failing](https://github.com/dabrahams/CBORCoding/actions/runs/6806944368/job/18509010389#step:4:99).  The CI job passes for some reason, which also needs to be corrected in the workflow file.

**Comment by dabrahams** [comment]
@christophhagen OK, fixing it for x64 macs was easy: https://github.com/christophhagen/CBORCoding/pull/1

**Comment by dabrahams** [comment]
@christophhagen And [here](https://github.com/SomeRandomiOSDev/CBORCoding/pull/24) is the PR that ensures failures in CI are actually reported.

**Comment by SomeRandomiOSDev** [comment]
@christophhagen I created a [release](https://github.com/SomeRandomiOSDev/CBORCoding/releases/tag/1.4.0) to address a lot of the issues that came up due to this repo being so out of date. Please rebase on this release and update this PR accordingly

**Comment by christophhagen** [comment]
Closing the PR due to #27.

**Pull request closed without merging**
